### ISSUE TITLE
fix some race conditions

### ISSUE THREAD

**Issue by Spacechild1** [Lucarda/pd-webserver#1]
a) In https://github.com/Lucarda/pd-webserver/blob/343cef5baa336c0e7c99376bea8b08e8f98d3e78/pd-webserver.c#L81 you should join the thread after setting the exit flag

b) the "started" flag must be set in Pd's thread (in `webserver_main` resp. `webserver_free`), otherwise the check in https://github.com/Lucarda/pd-webserver/blob/343cef5baa336c0e7c99376bea8b08e8f98d3e78/pd-webserver.c#L26 is not safe.

Also applies to websocketserver.

**Comment by Lucarda** [comment]
thanks!

I will study `pthread_join`.

I might come back to you for further pointers on this :)

**Comment by Lucarda** [comment]
@Spacechild1 I think https://github.com/Lucarda/pd-webserver/pull/2/files fixes the issue.
Can you give it a look?
:)

**Comment by Spacechild1** [comment]
I just had a quick look, but it looks good.

**Comment by Lucarda** [comment]
Thanks :)

**Comment by Lucarda** [comment]
closed via 89799da
